### PR TITLE
Add configurable switcher popup timeout (issue#15)

### PR DESCRIPTION
**Pull request by ebeem**
add configurable switcher popup timeout ([issue#15](https://github.com/mzur/gnome-shell-wsmatrix/issues/15))

### CODE REVIEW

**Comment by mzur** [comment]
Thanks again for your contribution! Can you please add this to the feature list in the readme as well? Please bear with me until I have time to properly review this PR.

**Comment by numpde** [comment]
Is this supposed to be in gnome-tweaks (ver 3.34.0)?

**Comment by ebeem** [comment]
@numpde I think this is too old, so most probably yeah,

**Comment by mzur** [comment]
Yes, this is available since GNOME 3.32.

**Comment by numpde** [comment]
I can set the number of workspaces in Tweaks, not much else, and there seems to be no relevant 'swticher' or 'workspace' or 'popup' or 'timeout' setting in dconf-editor. What am I missing?
ubuntu 20.04, gnome-shell 3.36.1, gnome-tweaks 3.34.0, dconf-editor 3.36.0

**Comment by mzur** [comment]
Have you installed the most recent version of this extension?

**Comment by numpde** [comment]
> Have you installed the most recent version of this extension?

facepalm. got it. thank you.

**Pull request merged**
