### PR TITLE
Switcher cache (improves performance)

### PR DESCRIPTION
**Pull request by ebeem**
I think this is a very interesting PR, it provides an option in settings to enable switcher caching. The GNOME team seems to be using something similar to improve `activities view` performance. I am still not 100% sure whether this will have any side effects or not, I have been playing with it for around and it seems to play well with the `Super+Tab` shortcut that displays the `AppSwitcher`, there is a code that prevents them from being shown up together, and so a one must be destroyed before displaying the other popup.

The motivation behind this PR is only the `show thumbnails` option, thumbnails seem to consume a lot of processing power to be generated, and current implementation **rerenders thumbnails** serveral times while displaying the `workspace switcher`.

Caching will only rerender the `workspace switcher`  if some settings changed or an expected update was detected, like the `style-changed` event. This will make first display of the switcher much slower than the next cached switcher display.

Here is a performance check
`note: the more the workspaces are, the longer time it takes the extension to create them, in a case of 5x5 grid the performance will be much worse. This test was conducted on a 3x3 grid `

```
with caching disabled and thumbnails enabled:
gnome-shell[40250]: time taken to display switcher 170 ms
gnome-shell[40250]: time taken to display switcher 148 ms
gnome-shell[40250]: style changed to 8
gnome-shell[40250]: time taken to display switcher 153 ms
gnome-shell[40250]: complete destroy
gnome-shell[40250]: time taken to display switcher 135 ms
gnome-shell[40250]: time taken to display switcher 145 ms
gnome-shell[40250]: style changed to 8
gnome-shell[40250]: time taken to display switcher 152 ms
gnome-shell[40250]: complete destroy
gnome-shell[40250]: time taken to display switcher 132 ms
gnome-shell[40250]: time taken to display switcher 146 ms
gnome-shell[40250]: style changed to 8
gnome-shell[40250]: time taken to display switcher 152 ms
gnome-shell[40250]: complete destroy
gnome-shell[40250]: time taken to display switcher 135 ms
gnome-shell[40250]: time taken to display switcher 146 ms
gnome-shell[40250]: style changed to 8
gnome-shell[40250]: time taken to display switcher 153 ms
gnome-shell[40250]: complete destroy
gnome-shell[40250]: time taken to display switcher 135 ms
gnome-shell[40250]: time taken to display switcher 147 ms
gnome-shell[40250]: style changed to 8
gnome-shell[40250]: time taken to display switcher 156 ms
gnome-shell[40250]: complete destroy

=========================================================

with caching enabled and thumbnails enabled:
gnome-shell[40250]: time taken to display switcher 140 ms
gnome-shell[40250]: time taken to display switcher 0 ms
gnome-shell[40250]: style changed to 8
gnome-shell[40250]: time taken to display switcher 159 ms
gnome-shell[40250]: simple destroy
gnome-shell[40250]: time taken to display switcher 0 ms
gnome-shell[40250]: simple destroy
gnome-shell[40250]: time taken to display switcher 1 ms
gnome-shell[40250]: simple destroy
gnome-shell[40250]: time taken to display switcher 0 ms
gnome-shell[40250]: simple destroy
gnome-shell[40250]: time taken to display switcher 1 ms
gnome-shell[40250]: simple destroy
gnome-shell[40250]: time taken to display switcher 1 ms
gnome-shell[40250]: time taken to display switcher 1 ms
gnome-shell[40250]: time taken to display switcher 1 ms
gnome-shell[40250]: time taken to display switcher 1 ms
gnome-shell[40250]: time taken to display switcher 0 ms
gnome-shell[40250]: simple destroy
gnome-shell[40250]: time taken to display switcher 0 ms
gnome-shell[40250]: time taken to display switcher 0 ms
gnome-shell[40250]: time taken to display switcher 0 ms
gnome-shell[40250]: time taken to display switcher 0 ms
gnome-shell[40250]: time taken to display switcher 1 ms
gnome-shell[40250]: simple destroy
gnome-shell[40250]: time taken to display switcher 0 ms
gnome-shell[40250]: simple destroy

=========================================================
=========================================================
=========================================================

with caching disabled and thumbnails disabled:
gnome-shell[40250]: time taken to display switcher 2 ms
gnome-shell[40250]: time taken to display switcher 4 ms
gnome-shell[40250]: time taken to display switcher 4 ms
gnome-shell[40250]: style changed to 8
gnome-shell[40250]: time taken to display switcher 5 ms
gnome-shell[40250]: complete destroy
gnome-shell[40250]: time taken to display switcher 4 ms
gnome-shell[40250]: time taken to display switcher 4 ms
gnome-shell[40250]: time taken to display switcher 4 ms
gnome-shell[40250]: style changed to 8
gnome-shell[40250]: time taken to display switcher 7 ms
gnome-shell[40250]: complete destroy
gnome-shell[40250]: time taken to display switcher 2 ms
gnome-shell[40250]: time taken to display switcher 3 ms
gnome-shell[40250]: time taken to display switcher 3 ms
gnome-shell[40250]: style changed to 8
gnome-shell[40250]: time taken to display switcher 4 ms
gnome-shell[40250]: complete destroy
gnome-shell[40250]: time taken to display switcher 2 ms
gnome-shell[40250]: time taken to display switcher 2 ms
gnome-shell[40250]: time taken to display switcher 3 ms
gnome-shell[40250]: style changed to 8
gnome-shell[40250]: time taken to display switcher 3 ms
gnome-shell[40250]: complete destroy
gnome-shell[40250]: time taken to display switcher 3 ms
gnome-shell[40250]: time taken to display switcher 3 ms
gnome-shell[40250]: time taken to display switcher 3 ms
gnome-shell[40250]: style changed to 8
gnome-shell[40250]: time taken to display switcher 4 ms
gnome-shell[40250]: time taken to display switcher 4 ms
gnome-shell[40250]: complete destroy

=========================================================

with caching enabled and thumbnails disabled:
gnome-shell[40250]: rerenderign switcher ...
gnome-shell[40250]: complete destroy
gnome-shell[40250]: time taken to display switcher 4 ms
gnome-shell[40250]: time taken to display switcher 5 ms
gnome-shell[40250]: time taken to display switcher 0 ms
gnome-shell[40250]: style changed to 8
gnome-shell[40250]: time taken to display switcher 8 ms
gnome-shell[40250]: simple destroy
gnome-shell[40250]: time taken to display switcher 1 ms
gnome-shell[40250]: time taken to display switcher 0 ms
gnome-shell[40250]: time taken to display switcher 0 ms
gnome-shell[40250]: simple destroy
gnome-shell[40250]: time taken to display switcher 0 ms
gnome-shell[40250]: time taken to display switcher 0 ms
gnome-shell[40250]: time taken to display switcher 0 ms
gnome-shell[40250]: time taken to display switcher 1 ms
gnome-shell[40250]: time taken to display switcher 0 ms
gnome-shell[40250]: time taken to display switcher 1 ms
gnome-shell[40250]: simple destroy
gnome-shell[40250]: time taken to display switcher 0 ms
gnome-shell[40250]: simple destroy
gnome-shell[40250]: time taken to display switcher 0 ms
gnome-shell[40250]: time taken to display switcher 0 ms
gnome-shell[40250]: time taken to display switcher 0 ms
gnome-shell[40250]: simple destroy

```

This PR needs more testing. Also, this feature is disabled by default, and must be enabled in preferences.

### CODE REVIEW

**Comment by mzur** [comment]
Interesting. The delay is not as high on my machine but the improvement with the caching is still obvious:

```
gnome-shell[1088]: time taken to display switcher 48 ms
gnome-shell[1088]: time taken to display switcher 59 ms
gnome-shell[1088]: style changed to 8
gnome-shell[1088]: time taken to display switcher 67 ms
gnome-shell[1088]: time taken to display switcher 63 ms
gnome-shell[1088]: time taken to display switcher 61 ms
gnome-shell[1088]: time taken to display switcher 63 ms
gnome-shell[1088]: time taken to display switcher 63 ms
gnome-shell[1088]: time taken to display switcher 65 ms
gnome-shell[1088]: time taken to display switcher 63 ms
gnome-shell[1088]: time taken to display switcher 60 ms
gnome-shell[1088]: time taken to display switcher 62 ms
gnome-shell[1088]: time taken to display switcher 63 ms
gnome-shell[1088]: time taken to display switcher 65 ms
gnome-shell[1088]: time taken to display switcher 60 ms
gnome-shell[1088]: time taken to display switcher 61 ms
gnome-shell[1088]: time taken to display switcher 60 ms
gnome-shell[1088]: time taken to display switcher 62 ms
gnome-shell[1088]: complete destroy

-- enable caching, restart gnome --

gnome-shell[1088]: time taken to display switcher 51 ms
gnome-shell[1088]: time taken to display switcher 0 ms
gnome-shell[1088]: style changed to 8
gnome-shell[1088]: time taken to display switcher 63 ms
gnome-shell[1088]: rerenderign switcher ...
gnome-shell[1088]: complete destroy
gnome-shell[1088]: time taken to display switcher 48 ms
gnome-shell[1088]: time taken to display switcher 0 ms
gnome-shell[1088]: style changed to 8
gnome-shell[1088]: time taken to display switcher 58 ms
gnome-shell[1088]: time taken to display switcher 1 ms
gnome-shell[1088]: time taken to display switcher 0 ms
gnome-shell[1088]: time taken to display switcher 0 ms
gnome-shell[1088]: time taken to display switcher 0 ms
gnome-shell[1088]: time taken to display switcher 1 ms
gnome-shell[1088]: time taken to display switcher 0 ms
gnome-shell[1088]: time taken to display switcher 1 ms
gnome-shell[1088]: time taken to display switcher 0 ms
gnome-shell[1088]: time taken to display switcher 1 ms
gnome-shell[1088]: time taken to display switcher 0 ms
gnome-shell[1088]: time taken to display switcher 0 ms
gnome-shell[1088]: time taken to display switcher 0 ms
gnome-shell[1088]: time taken to display switcher 1 ms
gnome-shell[1088]: simple destroy
```

I'll have a closer look at your code later.

**Comment by ebeem** [comment]
I noticed having more windows open and more workspaces count, makes rendering the switcher slower.
So if you have a 5x5 grid, it will take much longer to render the thumbnails.

My case above is 3x3 grid with many windows open.

**Comment by mzur** [comment]
Okay, here are my comments:

1. I don't like this as an optional feature. Either it works well and is always enabled or it doesn't work well and is not implemented at all.
2. I believe the switcher without thumbnails isn't worth bothering. The difference between 5 ms and 1 ms is not noticeable, I'd say.
3. I think the switcher should still be destroyed properly so it doesn't take up any resources when it is not needed. In my opinion, the initial delay when the switcher is opened is less critical than the delay when workspaces are switched.

Based on your code and these comments, I implemented a simplified mechanism for the caching in 
c4c0147. There is no caching for the switcher without thumbnails and the switcher takes a little longer to render initially. What do you think of that?

Here are the timings for a 5x5 grid:
```
-- without caching --
gnome-shell[1106]: time taken to display switcher 96 ms (initialize)
gnome-shell[1106]: time taken to display switcher 110 ms
gnome-shell[1106]: time taken to display switcher 127 ms
gnome-shell[1106]: time taken to display switcher 126 ms
gnome-shell[1106]: time taken to display switcher 124 ms
gnome-shell[1106]: time taken to display switcher 130 ms
gnome-shell[1106]: time taken to display switcher 103 ms
gnome-shell[1106]: time taken to display switcher 113 ms
gnome-shell[1106]: time taken to display switcher 137 ms
gnome-shell[1106]: time taken to display switcher 129 ms
gnome-shell[1106]: time taken to display switcher 129 ms
gnome-shell[1106]: time taken to display switcher 130 ms
gnome-shell[1106]: time taken to display switcher 92 ms (initialize)
gnome-shell[1106]: time taken to display switcher 111 ms
gnome-shell[1106]: time taken to display switcher 126 ms
gnome-shell[1106]: time taken to display switcher 125 ms
gnome-shell[1106]: time taken to display switcher 126 ms
gnome-shell[1106]: time taken to display switcher 131 ms

-- with caching --
gnome-shell[1106]: time taken to display switcher 98 ms (initialize)
gnome-shell[1106]: time taken to display switcher 1 ms
gnome-shell[1106]: time taken to display switcher 0 ms
gnome-shell[1106]: time taken to display switcher 1 ms
gnome-shell[1106]: time taken to display switcher 1 ms
gnome-shell[1106]: time taken to display switcher 1 ms
gnome-shell[1106]: time taken to display switcher 1 ms
gnome-shell[1106]: time taken to display switcher 1 ms
gnome-shell[1106]: time taken to display switcher 1 ms
gnome-shell[1106]: time taken to display switcher 1 ms
gnome-shell[1106]: time taken to display switcher 1 ms
gnome-shell[1106]: time taken to display switcher 96 ms (initialize)
gnome-shell[1106]: time taken to display switcher 0 ms
gnome-shell[1106]: time taken to display switcher 1 ms
gnome-shell[1106]: time taken to display switcher 0 ms
gnome-shell[1106]: time taken to display switcher 0 ms
gnome-shell[1106]: time taken to display switcher 1 ms
gnome-shell[1106]: time taken to display switcher 1 ms
gnome-shell[1106]: time taken to display switcher 0 ms
gnome-shell[1106]: time taken to display switcher 0 ms

-- without thumbnails and caching --
gnome-shell[1106]: time taken to display switcher 6 ms (initialize)
gnome-shell[1106]: time taken to display switcher 3 ms
gnome-shell[1106]: time taken to display switcher 2 ms
gnome-shell[1106]: time taken to display switcher 3 ms
gnome-shell[1106]: time taken to display switcher 3 ms
gnome-shell[1106]: time taken to display switcher 3 ms
gnome-shell[1106]: time taken to display switcher 4 ms
gnome-shell[1106]: time taken to display switcher 3 ms
gnome-shell[1106]: time taken to display switcher 6 ms (initialize)
gnome-shell[1106]: time taken to display switcher 3 ms
gnome-shell[1106]: time taken to display switcher 2 ms
gnome-shell[1106]: time taken to display switcher 3 ms
gnome-shell[1106]: time taken to display switcher 3 ms
gnome-shell[1106]: time taken to display switcher 4 ms
gnome-shell[1106]: time taken to display switcher 3 ms
gnome-shell[1106]: time taken to display switcher 3 m
```

**Comment by ebeem** [comment]
regarding point (1), I wanted to make this always enabled, but I couldn't completely make sure that this feature is stable and working with no bugs. The main reason why I am not confident about stability is because of point(3), I am caching the switcher and not destroying it.  I actually only did the `_redisplay` part first, which made a noticeable difference in performance for me. but after caching the switcher as well, it became very smooth, and it looked perfect to me.

I am pretty sure it works well if we discard the switcher caching part and keep the `_redisplay` only, but the optional experimental feature is there so others can test it and report bugs before we confidently enable it by default.

and point (2) is totally valid. I just wanted to have a solution that works for both, but it doesn't really have a great impact on performance.

so my opinion is, we can for now test the `_redisplay` part more and merge it with the master branch (without an option to enable/disable it), but it will be perfect if we test the switcher caching part more and try to merge it in the future. 
And as you said, the indicator part doesn't really need caching.

**Comment by mzur** [comment]
Alright, I agree that caching of the whole switcher could be done with a switch in the settings. I wouldn't call it experimental, though. People should file bugs either way if something isn't working. In my opinion this part should always be optional as it probably consumes a few MB more memory compared to a switcher that is always destroyed.

I'll go ahead and merge the "simple" caching which is always enabled. Can you please build the optional "full" caching on top of that in a new PR?

**Comment by ebeem** [comment]
sure, will make a PR for that in a couple of days

**Pull request closed without merging**
