### PR TITLE
Gnome 3.38 support

### PR DESCRIPTION
**Pull request by mzur**
Issues:

- [x] `_updateScrollAdjustment` in WorkspacesDisplayOverride has been replaced by `_activeWorkspaceChanged`

- [x] The `flags` argument has been [removed](https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/9b99b67feabef01cb30e89962e50c094952d8852) from allocate functions

- [x] `_updateWorkspaceActors` in WorkspacesViewOverride has been [removed](https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/96f63b08c245cacd48d8186204fd4c1a6921319a)

- [x] ~~In the overview, the indicator first jumps to its "original" position (where it would be if the extension wasn't used), and only then jumps to the correct position.~~ (upstream issue)

- [x] The active workspace indicator is positioned wrongly or cut off in the first row and column. Example:
    image

- [x] The workspace indicator animation of workspace change is incorrect in overview.

- [x] The gnome-shell workspace change animation is incorrect for horizontal (displayed as vertical).

### CODE REVIEW

**Comment by mzur** [comment]
@ebeem Do you have time to take a look at the third issue (WorkspacesViewOverride)?

**Comment by ebeem** [comment]
@mzur a little busy for 2 months.
I will check them out if needed once I have time.
My apologies.

**Comment by mzur** [comment]
Alright, no problem. I have little time myself and am not even using Gnome 3.38. Maybe someone else is willing to contribute, too.

**Comment by ElijahLynn** [comment]
Thanks for starting this. I am seeing:
image

And the log:
> Sep 18 16:43:12 archlinux gnome-shell[1263]: JS ERROR: TypeError: this._dialog is null
>                                              _onFocusChanged@resource:///org/gnome/shell/ui/closeDialog.js:135:9
>                                              actionMoveWorkspace@resource:///org/gnome/shell/ui/windowManager.js:2170:23
>                                              _showWorkspaceSwitcher@/home/elijah/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/WmOverride.js

So, I assume that this is because of the 3.38 update. I'll try to figure out how to install this locally to test and maybe even get it in my IDE to help out with it as I really miss the workspace overview now for a few weeks or so and have motivation to do so. 

Thanks again

**Comment by mzur** [comment]
@ElijahLynn It's great that you want to help! Take a look at the [developing instructions](https://github.com/mzur/gnome-shell-wsmatrix#developing) for how to get started. Make sure to switch to the `gnome-3.38` branch of this repository.

Your error might actually be something that wasn't reported yet.

**Comment by ElijahLynn** [comment]
> @ElijahLynn It's great that you want to help! Take a look at the [developing instructions](https://github.com/mzur/gnome-shell-wsmatrix#developing) for how to get started. Make sure to switch to the `gnome-3.38` branch of this repository.
> 
> Your error might actually be something that wasn't reported yet.

Thanks for that link, super helpful and seems clear on how to test this branch locally. I hope to get to it soon and will post back when/if I do.

**Comment by gowza** [comment]
I am running Gnome 3.38.1 on Arch Linux. I installed this `gnome-3.38` branch on my machine and the main feature is working fine. There is no extension error message.

I can confirm that the `The active workspace indicator is positioned wrongly or cut off in the first row and column` issue is there. 

Also I pick up on another issue on Activities view. The active workspace indicator box in Activities view is not drawn correctly.

output

I also get this error (from `journalctl /usr/bin/gnome-shell -f`) when navigating between workspaces in Activities view:
```
Oct 31 15:00:16 gowza-arch gnome-shell[922]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Oct 31 15:00:16 gowza-arch gnome-shell[922]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Oct 31 15:00:16 gowza-arch gnome-shell[922]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Oct 31 15:00:16 gowza-arch gnome-shell[922]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Oct 31 15:00:16 gowza-arch gnome-shell[922]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Oct 31 15:00:16 gowza-arch gnome-shell[922]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Oct 31 15:00:16 gowza-arch gnome-shell[922]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Oct 31 15:00:16 gowza-arch gnome-shell[922]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
```

P.S. Thank you for this plugin. I am just reporting to help out. I am not pushing for the fix. I appreciate the work that you have done already in maintaining such an awesome plugin.

**Comment by mzur** [comment]
@gowza Thanks for the report. The issue of your video seems to be what is described in the fourth bullet point of my first post here. Can you confirm that this issue occurred only after the GNOME 3.38 upgrade?

**Comment by gowza** [comment]
@mzur Yes. I can confirm that the issue occurred only after GNOME 3.38 upgrade. The issue goes away when I disable the extension.

**Comment by tom-james-watson** [comment]
Another regression is that the workspace switch animation in the overview is animating horizontally for vertical switches. It's similar to https://github.com/mzur/gnome-shell-wsmatrix/issues/56, but with the directions reversed.

**Comment by ebeem** [comment]
` In the overview, the indicator first jumps to its "original" position (where it would be if the extension wasn't used), and only then jumps to the correct position.`

Upstream issue according to my testing

**Comment by mzur** [comment]
I now removed the WorkspacesViewOverride entirely as it no longer had any effect. This probably means that the animations are incorrect again but I can't test this as I can't manage to enable animations in my test VM.

**Comment by ebeem** [comment]
Thanks @mzur, sorry for not helping in this.
I will try to look at it soon, it seems like we have two issues left.

- [ ] The active workspace indicator is positioned wrongly or cut off in the first row and column.
- [ ] The workspace indicator animation of workspace change is incorrect in overview.
- [ ] The gnome-shell workspace change animation is incorrect for horizontal (displayed as vertical).

Do we have any other issues?
It seems like gnome 40 is going to require a lot of changes in code, there are a lot of changes so far.

**Comment by mzur** [comment]
@ebeem: No worries, nobody is obliged to do anything here, after all. Yes, I think the animation issues are the only ones remaining. I just fixed the workspace indicator issue. Unfortunately, I can't debug the animation issues.

As to GNOME 40 I think we should initially remove all but the most basic features that no longer work there. For me, this means no support for a 2D workspace in the activity overview. This can be added later but I don't see that we can establish full support in a timely manner.

**Comment by gowza** [comment]
Hey @mzur. May I suggest we disable the indicator animation by always set the `indicatorWorkspace` to `activeWorkspace`.

https://github.com/mzur/gnome-shell-wsmatrix/blob/2c59c0b6ddfaf791bcf83269a88e6676b33e4b7d/wsmatrix%40martin.zurowietz.de/ThumbnailsBoxOverride.js#L203-L204

This will force the indicator drawing on the active workspace every time `allocate()` is called and got rid of the animation.

**Comment by mzur** [comment]
Thanks for the suggestion @gowza! @ebeem can you confirm that this would be a viable workaround?

**Comment by logankoester** [comment]
> Thanks for the suggestion @gowza! @ebeem can you confirm that this would be a viable workaround?

I just tried this idea and confirmed that this does remove the incorrect animation. Much nicer, thanks @gowza :+1: 

Tested on GNOME 40.0.0.

https://github.com/mzur/gnome-shell-wsmatrix/blob/ae318ddbe4c0530abee095faf6c6a8c8739a3d2c/wsmatrix%40martin.zurowietz.de/ThumbnailsBoxOverride.js#L201-L203

**Comment by mzur** [comment]
Thanks @logankoester! I'll look into your PR. So does this extension work out of the box with GNOME 40? Maybe you can provide some insight in #146.

**Comment by logankoester** [comment]
I've only been using it on 40 for an hour or two but everything seems good
to go from what I see so far.

I only commented a line out and replaced it with that stub in my PR, so if
you merge you might want to outright delete the line or add a comment.

**Comment by mzur** [comment]
I attempted a fix for the window animation direction on workspace change in the overview. Can someone please test if it works on their system as well (@tom-james-watson)? I saw some glitches but this might as well be related to my VM.

**Comment by wedeluxe** [comment]
My setup:

- GNOME Shell 3.38.4
- 3x3 Matrix

Tried your fix. When leaving the initial row, open windows disappear in the overview.

Details:

1. Open overview
2. When switching workspaces left and right, everything works as expected.
3. The moment I'm leaving the initial row (by moving a workspace up or down) all open-window-previews disappear.
4. When switching back to the initial row, the previews which were visible in step 2 do not reappear.

When opening the overview, the workspace matrix is displayed on the right side. On the left side GNOME shows a preview of all windows open on the current workspace. These previews disappear throughout the process.
The small workspace preview images within the workspace matrix stay visible and keep showing all open windows all the time.

**Comment by mzur** [comment]
The implementation for the fix continues in #149. I made some progress but the animation is still glitchy.

**Comment by mzur** [comment]
A fix or the animation was too much work. I now disabled that animation, too.

**Pull request merged**
