### PR TITLE
Implement complete switcher caching

### PR DESCRIPTION
**Pull request by ebeem**
as discussed in #24 and #26 
this is the caching part that we can't guarantee its stability

note: this feature is disabled by default, and must be enabled from the preferences.

### CODE REVIEW

**Comment by mzur** [comment]
I observed one weird thing: When I added a `log('HIDE')` to check if the hide/destroy works correctly, it would print `HIDE` whenever I switched windows with Alt+Tab. Apparently this action also calls `destroy` for the switcher popup if it still exists but I don't know where and why. Do you have an idea why this is? I guess we can merge this anyway but still...

**Comment by ebeem** [comment]
I checked this before, the app switcher (alt+tab) and workspaces switcher do NOT overlap. I think you can see this in the method `_startSwitcher` in `windowManager.js` if I am not mistaken
```Javascript
        /* prevent a corner case where both popups show up at once */
        if (this._workspaceSwitcherPopup != null)
            this._workspaceSwitcherPopup.destroy();
```

**Comment by mzur** [comment]
I see. This explains why `destroy` is called each time Alt+Tab is used and the switcher popup is hidden.

**Comment by mzur** [comment]
@ebeem Would you be interested in getting write access to this repository? I expect to have almost no time for maintenance in the next couple of months. It would be good to know that somebody else could also handle bug fixes or new issues. I'm not asking you to take over this repository, only to help with maintenance when I'm unresponsive and if you are willing and have the time :wink:

**Comment by ebeem** [comment]
@mzur Sure, I might not have time to implement new features for now, but since I rely on this extension a lot, I am ready to fix critical bugs and try my best to make this extension compatible with the latest stable version of `GNOME`

**Comment by mzur** [comment]
Great, thanks! I wasn't talking about new features, too, as I would like to still have a say in that in the future :wink:

**Pull request merged**
