### PR TITLE
Support multi-monitor setups

### PR DESCRIPTION
**Pull request by ebeem**
related to #21 and #46 

this was discussed before, but due to the many changes that have been implemented since the previous PR, it needed to be done again. the problems that were listed before are

- [ ]  Implement a better way to get thumbnails from monitors other than the primary. Current method seems to work fine, but it's probably going to cause conflicts with some extensions or cause some bugs at some point (best solution is to have GNOME support getting thumbnails from a specific monitor and workspace).
- [x] Improve the performance, the time needed to display the switchers is almost N times the time needed to display a single switcher, where n is the number of monitors.
- [x] Sync Switchers hide animation/destroy. Sometimes, a little delay in hiding switchers occurs, that's because each switcher has its own timeout in the current implementation (probably better be shared).

regarding `point#1`, I tried my best to keep the code as simple as possible. making   `GNOME` properly show thumbnails of workspaces is easy, but it will require more rewriting of methods from the class `WorkspaceThumbnail`.

I have been trying this for days, and it seems fine. However, I will feel more comfortable if anyone who is interested can test it as well.

### CODE REVIEW

**Comment by mzur** [comment]
> Current method seems to work fine, but it's probably going to cause conflicts with some extensions or cause some bugs at some point (best solution is to have GNOME support getting thumbnails from a specific monitor and workspace).

Do you mean the workaround with `Main.layoutManager.primaryIndex` in the WorkspaceThumbnail class or anything else?

I'll see if I can test this. I only have a VM for the newer versions of GNOME and I don't know if I can set it up for multiple monitors.

**Comment by ebeem** [comment]
yes, it's this part about changing the primary index and then restoring it after getting the thumbnail

**Comment by mzur** [comment]
I found that it's super easy to emulate multiple monitors with a VM. I'll have a look at this in the next few days.

**Comment by ebeem** [comment]
Great job!! thanks.
regarding the `GNOME 3.34` update, I have tested the extension under `GNOME 3.33.91` and it's working fine until now.

**Comment by mzur** [comment]
@ebeem Will you merge this? Are you even able to? :smile: I don't know what permissions you have got as collaborator in this repo.

**Comment by ebeem** [comment]
yes, I was able to merge 😆

**Pull request merged**
