### PR TITLE
Workspace overview

### PR DESCRIPTION
**Pull request by mzur**
This implements the workspace switcher popup as a simple workspace overview that does not automatically disappear (as discussed in #13).

video

I still get warnings like these in the log:
```
Window manager warning: Overwriting existing binding of keysym 37 with keysym 37 (keycode 10).
```
They seem to be caused by the new keybindings but I'm not sure. If this is the case, I don't know how to get rid of the warnings.

### CODE REVIEW

**Comment by mzur** [comment]
I didn't observe the warnings with GNOME 3.30 (#45) so the code is probably fine. I'll wait a few days if someone wants to comment and merge then.

**Comment by goodwillcoding** [comment]
@mzur : tested the branch, seems to work though wrap around in column/row mode seems to have been broken.

**Comment by goodwillcoding** [comment]
also when use Super+W for pop it is not "highlighting" which screen is selected.

**Comment by mzur** [comment]
Thanks for testing! I published a fix for the wraparound mode.

> also when use Super+W for pop it is not "highlighting" which screen is selected.

What do you mean by that? When I press <kbd>Super</kbd>+<kbd>W</kbd> the current workspace is highlighted (see video above).

**Comment by goodwillcoding** [comment]
I can confirm wrap around has been fixed

**Comment by goodwillcoding** [comment]
So here is the example of the current workspace not highlighted when Super+W triggerd overlay appears. As you can see I do not know which space I am on. This does not happen when I do no overlay navigation.

wsmatrix

Also as side note, you can see in a gif that it move a tad after appearance ... a tween?

**Comment by mzur** [comment]
I see, this only affects the overview when thumbnails are disabled. I opened a new issue for that ( #48 ).

Does the workspace switcher popup also move when you switch workspaces the usual way?

**Comment by goodwillcoding** [comment]
@mzur : so it was hard to tell originally it does move when doing regular workspace switching.

**Comment by mzur** [comment]
Does it also move if you disable this extension and use the default workspace switcher?

**Comment by mzur** [comment]
In that case this would be an upstream issue of GNOME or maybe your theme and not related to this extension. But thanks again for testing!

**Pull request merged**
