### PR TITLE
Fix overview compatibility with GNOME 3.36 (fixes #96)

### LINKED ISSUE #96: Workspace grid in overview is broken in Gnome 3.36
```
Mar 09 19:20:17 ebeem gnome-shell[2376]: JS WARNING: [/home/ebeem/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/OverviewOverride.js 78]: reference to undefined property "_controls"
Mar 09 19:20:17 ebeem gnome-shell[2376]: JS ERROR: Extension wsmatrix@martin.zurowietz.de: TypeError: Main.overview._controls is undefined
                                         _activateOverride@/home/ebeem/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/OverviewOverride.js:78:31
                                         _handleShowOverviewGridChanged@/home/ebeem/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/OverviewOverride.js:68:15
                                         OverviewOverride@/home/ebeem/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/OverviewOverride.js:21:12
                                         WsMatrixExtension@/home/ebeem/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/extension.js:13:31
                                         enable@/home/ebeem/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/extension.js:25:15

```

seems like the `Main.overview._controls` the extension uses to overwrite the overview is changed in `Gnome 3.36`

### PR DESCRIPTION
**Pull request by ebeem**
Resolves #96 

Issues: 
- [x] workspace switching animation in overview #56 & # #70
- [x] workspace indicator in overview is [not animating properly](https://salsa.debian.org/gnome-team/gnome-shell/-/commit/9c1940ef9db50ee693c2f82c8a2a4486bce1a1fe)

### CODE REVIEW

**Comment by mzur** [comment]
@ebeem Does the preferences window work for you? I already have this issue with another extension. The window doesn't show up and doesn't print any errors.

**Comment by mzur** [comment]
How are you testing this with GNOME 3.36 anyway? I use the daily build of Ubuntu 20.04 which has GNOME 3.35.91. This extension runs without issues there. At least with the features I can try without access to the preferences.

**Comment by mzur** [comment]
We should also update the `_showWorkspaceSwitcher` function to the curent state (and potentially other functions that override the original GNOME code). At a first glance the new GNOME version seems to introduce a new horizontal mode for workspaces.

**Comment by ebeem** [comment]
@mzur the preferences window is working fine, I use Arch Linux, and GNOME 3.36 landed yesterday.
regarding updating functions, yeah, I think it's a good idea to update all ones we override.

**Comment by ElijahLynn** [comment]
What should I be testing for on this PR? e.g. when I hit <super> should it show my grid? Right now it just shows the long column on the right with this PR. If there are windows it shows that overview of them, but not the grid I have set up.

**Comment by ElijahLynn** [comment]
> What should I be testing for on this PR? e.g. when I hit should it show my grid? Right now it just shows the long column on the right with this PR. If there are windows it shows that overview of them, but not the grid I have set up.

I see now the option in settings to show the grid in overview. So all is working well with this PR on my local. If you need anyone to test anything I'll keep watching this issue. 
image

image

**Comment by ebeem** [comment]
Thanks for testing @ElijahLynn 
it seems like this PR fixes everything so far. However, there one small issue.
GNOME 3.36 changed the way the indicator animates in the overview, now if you try to switch workspace while in the overview, the indicator will jump rather than animating to the target workspace.

The expected behavior is to show smooth animation, all main functionality is working so far, this is just complementary, but we want to fix it before merging.

Thanks

**Comment by ebeem** [comment]
a new bug showed up after a recent gnome-shell minor update
switch workspaces in overview now will not animate vertically #56 & # #70 

I am assuming gnome-shell is getting red of all Tweener animations, will need to investigate more.

**Comment by JohannesBe** [comment]
I get another error message than #96 :

```
JS ERROR: Extension wsmatrix@martin.zurowietz.de: Error: Tried to construct an object without a GType; are you using GObject.registerClass() when inheriting from a GObject type?
                                                  Settings@/home/*********/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/Settings.js:23:5
                                                  WsMatrixExtension@/home/*********/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/extension.js:10:22
                                                  enable@/home/*********/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/extension.js:25:15
                                                  _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:160:32
                                                  loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:311:26
                                                  callback@resource:///org/gnome/shell/ui/extensionDownloader.js:204:39
                                                  gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:97:13

```

**Comment by mzur** [comment]
@JohannesBe This looks like #98. Can you please check if you have the most recent version of this extension?

**Comment by mzur** [comment]
I set up an Arch VM with GNOME 3.36 to work on this but somehow I can't get the GNOME animations to work. Animations and 3D acceleration are enabled but still no animations, so I can't do any debugging on the animation issues here, sorry. But I'll look into updating the code.

**Comment by mzur** [comment]
@ebeem Is `WorkspacesViewOverride` necessary at all? The only thing it overrides is `_updateWorkspaceActors` and this seems to be doing exactly the same than the original class.

**Comment by JohannesBe** [comment]
Hi @mzur , for me the latest branch works just fine now, it started working after I installed new updates on Arch, so I assume something was broken upstream / I got an incomplete gnome transition installed.

**Comment by ebeem** [comment]
@mzur this was introduced in #70 to **fix workspace switching animation in overview**
However, it seems like a lot of animating code changed with this [commit](https://salsa.debian.org/gnome-team/gnome-shell/-/commit/9c1940ef9db50ee693c2f82c8a2a4486bce1a1fe)
so we will need to do more research in how the animating is handled now, we might not need `WorkspacesViewOverride` anymore as you mentioned, but I still can't confirm it yet.

We know for sure that the way animating is handled changed, but it seems to me like it's being handled by more than one class now.

**Comment by ebeem** [comment]
committed code to apply the fix for grid animation in the overview, this is still applied in `WorkspacesViewOverride`, so we still need to have this file.

we need to figure out a way to fix workspace indicator animation in the overview which definitely changed in [here](https://salsa.debian.org/gnome-team/gnome-shell/-/commit/9c1940ef9db50ee693c2f82c8a2a4486bce1a1fe), I accedintely referenced it in the earlier problem, this only affects indicator animation appearantly, not workspace transition animation.

**Comment by ebeem** [comment]
so far, it seems like animating the indicator won't be so easy.
The reason behind that is using the `St.Adjustment` object to animate scrolling in the indicator.
This component is poorly [docuemnted](https://developer.gnome.org/st/stable/api-index-full.html)

I will try to take a look at the source code and see if I can get something, it will need a lot of changes to get rid of the `St.Adjustment` and use the old `.ease` on the indicator to animate it as far as I am concerned.

**Comment by ebeem** [comment]
the current workaround is to disable indicator animation in the overview
by overriding this function in `WorkspacesDisplay.js`

```
   _updateScrollAdjustment(index) {
      if (this._gestureActive)
         return;

      this._scrollAdjustment.ease(index, {
         mode: Clutter.AnimationMode.EASE_OUT_CUBIC,
         duration: 1,
      });
   }
```

will appreciate it if someone else can look at it.

**Comment by ebeem** [comment]
@mzur please let me know if I should commit the workaround or wait until someone commits a real solution.

**Comment by mzur** [comment]
The disabled animation would be totally fine for me.

**Comment by ebeem** [comment]
great, I think all is good then, there is no more work from my side for 3.36 compatibility

**Comment by mzur** [comment]
Thanks a lot @ebeem! I'll take a last look at the code in the next days and will release it then.

**Pull request merged**
