### PR TITLE
Fix for overview animation

### PR DESCRIPTION
**Pull request by mzur**
This PR attempts to fix the last remaining issue of #125.

### CODE REVIEW

**Comment by wedeluxe** [comment]
Tested your recent changes. Looks good to me.
Window previews in the activity view remain visible.
When switching workspaces vertically, the animation moves vertically.
When switching workspaces horizontally, the animation moves horizontally.

**Comment by mzur** [comment]
The animation of the windows should be working now. One issue remains: If the overview is opened in a workspace row other than the first, the windows are initially not displayed.

**Comment by wedeluxe** [comment]
After logging back in from the lock screen the extension is not initialized (completely).

- Logically, workspaces are not organized in a matrix, instead I end up with a vertical array.
- I can only navigate up and down. Switching left and right can't be done.
- Shortcut <Super+W> doesn't work.
- When switching workspaces the overlay is a single column of 9 workspaces.
- In the activities overview the workspace matrix is still shown.

**Comment by wedeluxe** [comment]
Sorry to say, disappearing window previews in the activity overview are still around.

3x3 matrix
2 monitor setup

Previews on the secondary monitor have a tendency to disappear.
While the animation is drawn they are always(!) visible.
When the animation finishes they become invisible.
Happens not in every row / every column. The more you switch (without leaving the overview) the more weird it gets.

Hard to find patterns. I'll give it a try:

- When staying in the same row, the visibility remains the same.
- Behavior depends on the initial cell.

Another crazy finding – this also affects previews on the primary monitor:

- when ending in a cell with invisible previews on the secondary monitor
- press `Super` to leave the overview
- press `Super` to enter the overview
- previews on both monitors have disappeared

**Comment by mzur** [comment]
I decided to call the whole thing off and  disable the animation here, too.

**Pull request closed without merging**
